/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import com.google.zxing.WriterException;
import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaarduinoproyecto.Componente;
import jssc.SerialPortException;

/**
 *
 * @author diego
 */
public class Led extends javax.swing.JFrame {
    
    Componente Led = new Componente("https://www.steren.com.mx/led-de-5-mm-color-rojo-claro.html","/Imágenes/Conexion Leds.jpeg","datasheet",5);
    PanamaHitek_Arduino Arduino = new PanamaHitek_Arduino();
    String OutputR, OutputL;
    int R=0, L=0;
    
    public Led() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            Arduino.getPortsAvailable();
            Arduino.arduinoTX("/dev/ttyUSB0", 9600);
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jSlider_IL.setEnabled(false);
        jLabel_MI.setEnabled(false);
        jLabel2.setEnabled(false);
        jLabel_CI.setEnabled(false);
        jLabel3.setEnabled(false);
        jLabel4.setEnabled(false);
        jSlider_DL.setEnabled(false);
        jLabel5.setEnabled(false);
        jLabel_CD.setEnabled(false);
        
        BotonEncender.setEnabled(false);
        BotonApagar.setEnabled(false);
        BotonEncDer.setEnabled(false);
        BotonApagDer.setEnabled(false);
        BotonEncIzq.setEnabled(false);
        BotonApagIzq.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonEncender = new javax.swing.JButton();
        BotonApagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToggle_EA = new javax.swing.JToggleButton();
        jToggle_VI = new javax.swing.JToggleButton();
        jSlider_IL = new javax.swing.JSlider();
        jButton_Regresar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jLabel_MI = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_CI = new javax.swing.JLabel();
        BotonEncDer = new javax.swing.JButton();
        BotonApagDer = new javax.swing.JButton();
        BotonEncIzq = new javax.swing.JButton();
        BotonApagIzq = new javax.swing.JButton();
        jSlider_DL = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_CD = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BotonDiagrama = new javax.swing.JButton();
        BotonQR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(550, 745));
        setResizable(false);
        setSize(getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonEncender.setFont(new java.awt.Font("URW Gothic L", 0, 16)); // NOI18N
        BotonEncender.setText("Encender");
        BotonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEncenderActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEncender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 121, 60));

        BotonApagar.setFont(new java.awt.Font("URW Gothic L", 0, 16)); // NOI18N
        BotonApagar.setText("Apagar");
        BotonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 121, 60));

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 0, 36)); // NOI18N
        jLabel1.setText("TESTEO DE LEDS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 21, -1, -1));

        jToggle_EA.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jToggle_EA.setText("ENCENDER/APAGAR");
        jToggle_EA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggle_EAActionPerformed(evt);
            }
        });
        getContentPane().add(jToggle_EA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 40));

        jToggle_VI.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jToggle_VI.setText("VARIAR INTENSIDAD ");
        jToggle_VI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggle_VIStateChanged(evt);
            }
        });
        jToggle_VI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggle_VIActionPerformed(evt);
            }
        });
        getContentPane().add(jToggle_VI, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 299, 317, -1));

        jSlider_IL.setMajorTickSpacing(25);
        jSlider_IL.setMaximum(250);
        jSlider_IL.setPaintLabels(true);
        jSlider_IL.setPaintTicks(true);
        jSlider_IL.setValue(0);
        jSlider_IL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_ILStateChanged(evt);
            }
        });
        getContentPane().add(jSlider_IL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 500, 50));

        jButton_Regresar.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        jButton_Regresar.setText("REGRESAR");
        jButton_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 690, -1, -1));

        jButton_Salir.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        jButton_Salir.setText("SALIR");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, -1, -1));

        jLabel_MI.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        getContentPane().add(jLabel_MI, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel2.setText("Intensidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        jLabel_CI.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        getContentPane().add(jLabel_CI, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        BotonEncDer.setFont(new java.awt.Font("URW Gothic L", 0, 16)); // NOI18N
        BotonEncDer.setText("Encender derecho");
        BotonEncDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEncDerActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEncDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 190, 60));

        BotonApagDer.setFont(new java.awt.Font("URW Gothic L", 0, 16)); // NOI18N
        BotonApagDer.setText("Apagar derecha");
        BotonApagDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonApagDerActionPerformed(evt);
            }
        });
        getContentPane().add(BotonApagDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 190, 60));

        BotonEncIzq.setFont(new java.awt.Font("URW Gothic L", 0, 16)); // NOI18N
        BotonEncIzq.setText("Encender izquierdo");
        BotonEncIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEncIzqActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEncIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 60));

        BotonApagIzq.setFont(new java.awt.Font("URW Gothic L", 0, 16)); // NOI18N
        BotonApagIzq.setText("Apagar izquierdo");
        BotonApagIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonApagIzqActionPerformed(evt);
            }
        });
        getContentPane().add(BotonApagIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 60));

        jSlider_DL.setMajorTickSpacing(25);
        jSlider_DL.setMaximum(250);
        jSlider_DL.setPaintLabels(true);
        jSlider_DL.setPaintTicks(true);
        jSlider_DL.setValue(0);
        jSlider_DL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_DLStateChanged(evt);
            }
        });
        getContentPane().add(jSlider_DL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 510, -1));

        jLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel3.setText("Variador de Led Izquierdo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel4.setText("Variador de Led Derecho");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, -1));

        jLabel5.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel5.setText("Intensidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, -1, -1));

        jLabel_CD.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        getContentPane().add(jLabel_CD, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Odyssey.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Midnight.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        BotonDiagrama.setText("Diagrama");
        BotonDiagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDiagramaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDiagrama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 680, 90, 50));

        BotonQR.setText("Generar QR");
        BotonQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonQRActionPerformed(evt);
            }
        });
        getContentPane().add(BotonQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 682, -1, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEncenderActionPerformed
        try {
            Arduino.sendData("e");
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonEncenderActionPerformed

    private void BotonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonApagarActionPerformed
        try {
            Arduino.sendData("a");
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonApagarActionPerformed

    private void jToggle_EAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggle_EAActionPerformed
        if(jToggle_EA.isSelected()){
            jSlider_IL.setEnabled(false);
            jLabel_MI.setEnabled(false);
            jLabel2.setEnabled(false);
            jLabel_CI.setEnabled(false);
            jLabel3.setEnabled(false);
            jLabel4.setEnabled(false);
            jSlider_DL.setEnabled(false);
            jLabel5.setEnabled(false);
            jLabel_CD.setEnabled(false);
            
            jToggle_EA.setEnabled(true);
            BotonEncender.setEnabled(true);
            BotonApagar.setEnabled(true);
            BotonEncDer.setEnabled(true);
            BotonApagDer.setEnabled(true);
            BotonEncIzq.setEnabled(true);
            BotonApagIzq.setEnabled(true);
        }
        else{
            /*jToggle_VI.setEnabled(true);
            jSlider_IL.setEnabled(true);
            jLabel_MI.setEnabled(true);
            jLabel2.setEnabled(true);
            jLabel_CI.setEnabled(true);
            jLabel3.setEnabled(true);
            jLabel4.setEnabled(true);
            jSlider_DL.setEnabled(true);
            jLabel5.setEnabled(true);
            jLabel_CD.setEnabled(true);*/
            
            BotonEncender.setEnabled(false);
            BotonApagar.setEnabled(false);
            BotonEncDer.setEnabled(false);
            BotonApagDer.setEnabled(false);
            BotonEncIzq.setEnabled(false);
            BotonApagIzq.setEnabled(false);
        }
    }//GEN-LAST:event_jToggle_EAActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        try {
            Arduino.sendData("a");
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.exit(0);
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jToggle_VIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggle_VIActionPerformed
        if(jToggle_VI.isSelected()){
            BotonEncender.setEnabled(false);
            BotonApagar.setEnabled(false);
            BotonEncDer.setEnabled(false);
            BotonApagDer.setEnabled(false);
            BotonEncIzq.setEnabled(false);
            BotonApagIzq.setEnabled(false);
            
            jToggle_VI.setEnabled(true);
            jSlider_IL.setEnabled(true);
            jLabel_MI.setEnabled(true);
            jLabel2.setEnabled(true);
            jLabel_CI.setEnabled(true);
            jLabel3.setEnabled(true);
            jLabel4.setEnabled(true);
            jSlider_DL.setEnabled(true);
            jLabel5.setEnabled(true);
            jLabel_CD.setEnabled(true);
        }
        else{
            /*jToggle_EA.setEnabled(true);
            BotonEncender.setEnabled(true);
            BotonApagar.setEnabled(true);
            BotonEncDer.setEnabled(true);
            BotonApagDer.setEnabled(true);
            BotonEncIzq.setEnabled(true);
            BotonApagIzq.setEnabled(true);*/
            
            jSlider_IL.setEnabled(false);
            jLabel_MI.setEnabled(false);
            jLabel2.setEnabled(false);
            jLabel_CI.setEnabled(false);
            jLabel3.setEnabled(false);
            jLabel4.setEnabled(false);
            jSlider_DL.setEnabled(false);
            jLabel5.setEnabled(false);
            jLabel_CD.setEnabled(false);
        }
    }//GEN-LAST:event_jToggle_VIActionPerformed

    private void jSlider_ILStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_ILStateChanged
        L = jSlider_IL.getValue();
        String valor_tL = Integer.toString(L);
        
        jLabel_CI.setText(valor_tL);
        
        if (L < 10) {
        OutputL = "L" + "00" + L;
        } else if (L < 100) {
        OutputL = "L" + "0" + L;
        } else {
        OutputL = "L" + L;
        }
        
        try {
            System.out.println(OutputL);
            Arduino.sendData(OutputL);
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSlider_ILStateChanged

    private void jSlider_DLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_DLStateChanged
        R = jSlider_DL.getValue();
        String valor_tD = Integer.toString(R);
        
        jLabel_CD.setText(valor_tD);
        
        if (R < 10) {
        OutputR = "R" + "00" + R;
        } else if (R < 100) {
        OutputR = "R" + "0" + R;
        } else {
        OutputR = "R" + R;
        }
        
        try {
            System.out.println(OutputR);
            Arduino.sendData(OutputR);
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSlider_DLStateChanged

    private void jToggle_VIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggle_VIStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggle_VIStateChanged

    private void BotonEncDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEncDerActionPerformed
        try {
            Arduino.sendData("D");
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonEncDerActionPerformed

    private void BotonApagDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonApagDerActionPerformed
        try {
            Arduino.sendData("d");
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonApagDerActionPerformed

    private void BotonEncIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEncIzqActionPerformed
        try {
            Arduino.sendData("I");
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonEncIzqActionPerformed

    private void BotonApagIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonApagIzqActionPerformed
        try {
            Arduino.sendData("i");
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonApagIzqActionPerformed

    private void jButton_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegresarActionPerformed
        try {
            Arduino.sendData("a");
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            Arduino.killArduinoConnection();
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        MenuInicial Menu = new MenuInicial();
        Menu.show();
        this.hide();
    }//GEN-LAST:event_jButton_RegresarActionPerformed

    private void BotonDiagramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDiagramaActionPerformed
        // TODO add your handling code here:
        Diagrama conexion = new Diagrama(Led.diagrama);
        conexion.setVisible(true);
    }//GEN-LAST:event_BotonDiagramaActionPerformed

    private void BotonQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonQRActionPerformed
        // TODO add your handling code here:
        try {
            Ventana ventana = new Ventana(Led.linkQR);
            
            ventana.setVisible(true);
            
        } catch (WriterException ex) {
            Logger.getLogger(TestSensorIR.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }//GEN-LAST:event_BotonQRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Led.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Led.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Led.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Led.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Led().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonApagDer;
    private javax.swing.JButton BotonApagIzq;
    private javax.swing.JButton BotonApagar;
    private javax.swing.JButton BotonDiagrama;
    private javax.swing.JButton BotonEncDer;
    private javax.swing.JButton BotonEncIzq;
    private javax.swing.JButton BotonEncender;
    private javax.swing.JButton BotonQR;
    private javax.swing.JButton jButton_Regresar;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_CD;
    private javax.swing.JLabel jLabel_CI;
    private javax.swing.JLabel jLabel_MI;
    private javax.swing.JSlider jSlider_DL;
    private javax.swing.JSlider jSlider_IL;
    private javax.swing.JToggleButton jToggle_EA;
    private javax.swing.JToggleButton jToggle_VI;
    // End of variables declaration//GEN-END:variables
}
