/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import com.google.zxing.WriterException;
import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaarduinoproyecto.Componente;
import jssc.SerialPortException;

/**
 *
 * @author diegomg
 */
public class Motores extends javax.swing.JFrame {

    Componente Motor = new Componente("https://www.steren.com.mx/mini-motor-de-corriente-directa.html", "/Imágenes/Conexion Motor.jpeg", "datasheet", 5);
    int PWM_I = 0, PWM_D = 0, PWM_J = 0;
    String OutputPWM_I, OutputPWM_D, OutputPWM_J;
    PanamaHitek_Arduino Arduino = new PanamaHitek_Arduino();

    public Motores() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            Arduino.getPortsAvailable();
            Arduino.arduinoTX("/dev/ttyUSB0", 9600);
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }

        jLabel5.setEnabled(false);
        jLabel_PWM_JUNT.setEnabled(false);
        jSlider_PWM_JUNT.setEnabled(false);
        jSlider_PWM_JUNT.setValue(0);

        jLabel3.setEnabled(false);
        jLabel_PWM_IZQ.setEnabled(false);
        jSlider_PWM_IZQ.setEnabled(false);
        jLabel4.setEnabled(false);
        jLabel_PWM_DER.setEnabled(false);
        jSlider_PWM_DER.setEnabled(false);
        jSlider_PWM_IZQ.setValue(0);
        jSlider_PWM_DER.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSlider_PWM_IZQ = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSlider_PWM_DER = new javax.swing.JSlider();
        jToggle_MOT_INDIV = new javax.swing.JToggleButton();
        jToggle_MOT_JUNT = new javax.swing.JToggleButton();
        jLabel_PWM_IZQ = new javax.swing.JLabel();
        jLabel_PWM_DER = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSlider_PWM_JUNT = new javax.swing.JSlider();
        jLabel_PWM_JUNT = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BotonDiagrana = new javax.swing.JButton();
        BotonQR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(485, 655));
        setSize(getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 0, 36)); // NOI18N
        jLabel1.setText("TESTEO DE MOTORES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jSlider_PWM_IZQ.setMajorTickSpacing(25);
        jSlider_PWM_IZQ.setMaximum(250);
        jSlider_PWM_IZQ.setPaintLabels(true);
        jSlider_PWM_IZQ.setPaintTicks(true);
        jSlider_PWM_IZQ.setValue(0);
        jSlider_PWM_IZQ.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_PWM_IZQStateChanged(evt);
            }
        });
        getContentPane().add(jSlider_PWM_IZQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 191, 420, -1));

        jLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        jLabel3.setText("PWM MOTOR IZQUIERDO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 154, -1, -1));

        jLabel4.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        jLabel4.setText("PWM MOTOR DERECHO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 271, -1, -1));

        jSlider_PWM_DER.setMajorTickSpacing(25);
        jSlider_PWM_DER.setMaximum(250);
        jSlider_PWM_DER.setPaintLabels(true);
        jSlider_PWM_DER.setPaintTicks(true);
        jSlider_PWM_DER.setValue(0);
        jSlider_PWM_DER.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_PWM_DERStateChanged(evt);
            }
        });
        getContentPane().add(jSlider_PWM_DER, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 308, 420, -1));

        jToggle_MOT_INDIV.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        jToggle_MOT_INDIV.setText("TESTEO DE MOTORES INDIVIDUALES");
        jToggle_MOT_INDIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggle_MOT_INDIVActionPerformed(evt);
            }
        });
        getContentPane().add(jToggle_MOT_INDIV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 45));

        jToggle_MOT_JUNT.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        jToggle_MOT_JUNT.setText("TESTEO DE MOTORES JUNTOS");
        jToggle_MOT_JUNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggle_MOT_JUNTActionPerformed(evt);
            }
        });
        getContentPane().add(jToggle_MOT_JUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 317, 45));

        jLabel_PWM_IZQ.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        getContentPane().add(jLabel_PWM_IZQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 154, -1, -1));

        jLabel_PWM_DER.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        getContentPane().add(jLabel_PWM_DER, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        jLabel5.setText("PWM MOTORES JUNTOS:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 462, -1, -1));

        jSlider_PWM_JUNT.setMajorTickSpacing(25);
        jSlider_PWM_JUNT.setMaximum(250);
        jSlider_PWM_JUNT.setPaintLabels(true);
        jSlider_PWM_JUNT.setPaintTicks(true);
        jSlider_PWM_JUNT.setValue(0);
        jSlider_PWM_JUNT.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_PWM_JUNTStateChanged(evt);
            }
        });
        getContentPane().add(jSlider_PWM_JUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 499, 420, -1));

        jLabel_PWM_JUNT.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        getContentPane().add(jLabel_PWM_JUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, -1));

        jButton1.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, -1, -1));

        jButton2.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, -1, -1));

        BotonDiagrana.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        BotonDiagrana.setText("Diagrama");
        BotonDiagrana.setToolTipText("");
        BotonDiagrana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDiagranaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDiagrana, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 120, -1));

        BotonQR.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        BotonQR.setText("GenerarQR");
        BotonQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonQRActionPerformed(evt);
            }
        });
        getContentPane().add(BotonQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggle_MOT_INDIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggle_MOT_INDIVActionPerformed
        if (jToggle_MOT_INDIV.isSelected()) {
            jLabel5.setEnabled(false);
            jLabel_PWM_JUNT.setEnabled(false);
            jSlider_PWM_JUNT.setEnabled(false);
            jSlider_PWM_JUNT.setValue(0);

            jLabel3.setEnabled(true);
            jLabel_PWM_IZQ.setEnabled(true);
            jSlider_PWM_IZQ.setEnabled(true);
            jLabel4.setEnabled(true);
            jLabel_PWM_DER.setEnabled(true);
            jSlider_PWM_DER.setEnabled(true);
        } else {
            /*jToggle_MOT_JUNT.setEnabled(true);
            jLabel5.setEnabled(true);
            jLabel_PWM_JUNT.setEnabled(true);
            jSlider_PWM_JUNT.setEnabled(true);
            jLabel6.setEnabled(true);
            jLabel8.setEnabled(true);
            jToggle_INV_JUNT.setEnabled(true);*/

            jLabel3.setEnabled(false);
            jLabel_PWM_IZQ.setEnabled(false);
            jSlider_PWM_IZQ.setEnabled(false);
            jLabel4.setEnabled(false);
            jLabel_PWM_DER.setEnabled(false);
            jSlider_PWM_DER.setEnabled(false);

            try {
                System.out.println("S");
                Arduino.sendData("S");
            } catch (ArduinoException ex) {
                Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jToggle_MOT_INDIVActionPerformed

    private void jToggle_MOT_JUNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggle_MOT_JUNTActionPerformed
        if (jToggle_MOT_JUNT.isSelected()) {
            jLabel3.setEnabled(false);
            jLabel_PWM_IZQ.setEnabled(false);
            jSlider_PWM_IZQ.setEnabled(false);
            jLabel4.setEnabled(false);
            jLabel_PWM_DER.setEnabled(false);
            jSlider_PWM_DER.setEnabled(false);
            jSlider_PWM_IZQ.setValue(0);
            jSlider_PWM_DER.setValue(0);

            jLabel5.setEnabled(true);
            jLabel_PWM_JUNT.setEnabled(true);
            jSlider_PWM_JUNT.setEnabled(true);
        } else {
            /*jToggle_MOT_INDIV.setEnabled(true);
            jLabel3.setEnabled(true);
            jLabel_PWM_IZQ.setEnabled(true);
            jSlider_PWM_IZQ.setEnabled(true);
            jLabel9.setEnabled(true);
            jLabel10.setEnabled(true);
            jToggle_INV_IZQ.setEnabled(true);
            jLabel4.setEnabled(true);
            jLabel_PWM_DER.setEnabled(true);
            jSlider_PWM_DER.setEnabled(true);
            jLabel2.setEnabled(true);
            jLabel7.setEnabled(true);
            jToggle_INV_DER.setEnabled(true);*/

            jLabel5.setEnabled(false);
            jLabel_PWM_JUNT.setEnabled(false);
            jSlider_PWM_JUNT.setEnabled(false);
            jSlider_PWM_JUNT.setValue(0);

            try {
                System.out.println("S");
                Arduino.sendData("S");
            } catch (ArduinoException ex) {
                Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SerialPortException ex) {
                Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jToggle_MOT_JUNTActionPerformed

    private void jSlider_PWM_IZQStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_PWM_IZQStateChanged
        PWM_I = jSlider_PWM_IZQ.getValue();
        String Value_PWM_I = Integer.toString(PWM_I);
        jLabel_PWM_IZQ.setText(Value_PWM_I);

        if (PWM_I < 10) {
            OutputPWM_I = "P" + "00" + PWM_I;
        } else if (PWM_I < 100) {
            OutputPWM_I = "P" + "0" + PWM_I;
        } else {
            OutputPWM_I = "P" + PWM_I;
        }

        try {
            System.out.println(OutputPWM_I);
            Arduino.sendData(OutputPWM_I);
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSlider_PWM_IZQStateChanged

    private void jSlider_PWM_DERStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_PWM_DERStateChanged
        PWM_D = jSlider_PWM_DER.getValue();
        String Value_PWM_D = Integer.toString(PWM_D);
        jLabel_PWM_DER.setText(Value_PWM_D);

        if (PWM_D < 10) {
            OutputPWM_D = "W" + "00" + PWM_D;
        } else if (PWM_D < 100) {
            OutputPWM_D = "W" + "0" + PWM_D;
        } else {
            OutputPWM_D = "W" + PWM_D;
        }

        try {
            System.out.println(OutputPWM_D);
            Arduino.sendData(OutputPWM_D);
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSlider_PWM_DERStateChanged

    private void jSlider_PWM_JUNTStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_PWM_JUNTStateChanged
        PWM_J = jSlider_PWM_JUNT.getValue();
        String Value_PWM_J = Integer.toString(PWM_J);
        jLabel_PWM_JUNT.setText(Value_PWM_J);

        if (PWM_J < 10) {
            OutputPWM_J = "J" + "00" + PWM_J;
        } else if (PWM_J < 100) {
            OutputPWM_J = "J" + "0" + PWM_J;
        } else {
            OutputPWM_J = "J" + PWM_J;
        }

        try {
            System.out.println(OutputPWM_J);
            Arduino.sendData(OutputPWM_J);
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SerialPortException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSlider_PWM_JUNTStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Arduino.killArduinoConnection();
        } catch (ArduinoException ex) {
            Logger.getLogger(Led.class.getName()).log(Level.SEVERE, null, ex);
        }

        MenuInicial Menu = new MenuInicial();
        Menu.show();
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BotonDiagranaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDiagranaActionPerformed
        // TODO add your handling code here:
        Diagrama conexion = new Diagrama(Motor.diagrama);
        conexion.setVisible(true);
    }//GEN-LAST:event_BotonDiagranaActionPerformed

    private void BotonQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonQRActionPerformed
        // TODO add your handling code here:
        try {
            Ventana ventana = new Ventana(Motor.linkQR);

            ventana.setVisible(true);

        } catch (WriterException ex) {
            Logger.getLogger(TestSensorIR.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_BotonQRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Motores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Motores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Motores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Motores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Motores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDiagrana;
    private javax.swing.JButton BotonQR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_PWM_DER;
    private javax.swing.JLabel jLabel_PWM_IZQ;
    private javax.swing.JLabel jLabel_PWM_JUNT;
    private javax.swing.JSlider jSlider_PWM_DER;
    private javax.swing.JSlider jSlider_PWM_IZQ;
    private javax.swing.JSlider jSlider_PWM_JUNT;
    private javax.swing.JToggleButton jToggle_MOT_INDIV;
    private javax.swing.JToggleButton jToggle_MOT_JUNT;
    // End of variables declaration//GEN-END:variables
}
